#!/bin/bash

#python generate_analysis_of_seed.py config_CPG3_MOD_10.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_27.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_44.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_45.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_47.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_54.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_75.ini
#python generate_analysis_of_seed.py config_CPG3_MOD_95.ini

#python generate_analysis_of_seed.py config_BEER_BEST_CPG3.ini
#python generate_analysis_of_seed.py config_CPG3_30.ini
#python generate_analysis_of_seed.py config_CPG3_STD_35.ini

python generate_analysis_of_seed.py config_RPG3_STD_16.ini
python generate_analysis_of_seed.py config_RPG3_STD_4.ini
python generate_analysis_of_seed.py config_RPG3_STD_56.ini
python generate_analysis_of_seed.py config_RPG3_STD_61.ini
python generate_analysis_of_seed.py config_RPG3_STD_69.ini
python generate_analysis_of_seed.py config_RPG3_STD_71.ini
python generate_analysis_of_seed.py config_RPG3_STD_72.ini
python generate_analysis_of_seed.py config_RPG3_STD_75.ini